export const ingredients = [
  {
    id: 1,
    name: 'Cheese stuffed rim',
    price: 1,
    imageUrl: '/images/products/ingredients/cheese_rim.png',
  },
  {
    id: 2,
    name: 'Mozzarella',
    price: 1,
    imageUrl: '/images/products/ingredients/mozzarella.png',
  },
  {
    id: 3,
    name: 'Cheddar and Parmesan',
    price: 2,
    imageUrl: '/images/products/ingredients/cheddar_parmesan.png',
  },
  {
    id: 4,
    name: 'Jalapeno Pepper',
    price: 1,
    imageUrl: '/images/products/ingredients/jalapeno_pepper.png',
  },
  {
    id: 5,
    name: 'Tender chick',
    price: 2,
    imageUrl: '/images/products/ingredients/tender_chick.png',
  },
  {
    id: 6,
    name: 'Champignons',
    price: 1,
    imageUrl: '/images/products/ingredients/champignons.png',
  },
  {
    id: 7,
    name: 'Ham',
    price: 2,
    imageUrl: '/images/products/ingredients/ham.png',
  },
  {
    id: 8,
    name: 'Spicy pepperoni',
    price: 1,
    imageUrl: '/images/products/ingredients/spicy_pepperoni.png',
  },
  {
    id: 9,
    name: 'Spicy Chorizo',
    price: 2,
    imageUrl: '/images/products/ingredients/spicy_chorizo.png',
  },
  {
    id: 10,
    name: 'Pickled cucumbers',
    price: 1,
    imageUrl: '/images/products/ingredients/pickled_ cucumbers.png',
  },
  {
    id: 11,
    name: 'Fresh tomatoes',
    price: 1,
    imageUrl: '/images/products/ingredients/fresh_tomatoes.png',
  },
  {
    id: 12,
    name: 'Red onion',
    price: 1,
    imageUrl: '/images/products/ingredients/red_onion.png',
  },
  {
    id: 13,
    name: 'Juicy pineapples',
    price: 2,
    imageUrl: '/images/products/ingredients/juicy_pineapples.png',
  },
  {
    id: 14,
    name: 'Italian herbs',
    price: 1,
    imageUrl: '/images/products/ingredients/italian_herbs.png',
  },
  {
    id: 15,
    name: 'Sweet pepper',
    price: 1,
    imageUrl: '/images/products/ingredients/sweet_pepper.png',
  },
  {
    id: 16,
    name: 'Feta cubes',
    price: 2,
    imageUrl: '/images/products/ingredients/feta_cubes.png',
  },
  {
    id: 17,
    name: 'Meatballs',
    price: 3,
    imageUrl: '/images/products/ingredients/meatballs.png',
  },
  {
    id: 18,
    name: 'Bavarian sausages',
    price: 3,
    imageUrl: '/images/products/ingredients/bavarian_sausages.png',
  },
  {
    id: 19,
    name: 'Spicy beef',
    price: 2,
    imageUrl: '/images/products/ingredients/spicy_beef.png',
  },
  {
    id: 20,
    name: 'Shrimps',
    price: 3,
    imageUrl: '/images/products/ingredients/shrimps.png',
  },
].map(({ name, price, imageUrl }) => ({ name, price, imageUrl }));