export const products = [
  // Breakfast
  {
    id: 1,
    name: 'Ham Omelette',
    imageUrl: '/images/products/breakfast/omelette_ham.webp',
    categoryId: 2,
  },
  {
    id: 2,
    name: 'Pepperoni Omelette',
    imageUrl: '/images/products/breakfast/omelette_pepperoni.webp',
    categoryId: 2,
  },
  {
    id: 3,
    name: 'Bacon Omelette',
    imageUrl: '/images/products/breakfast/omelette_bacon.webp',
    categoryId: 2,
  },
  {
    id: 4,
    name: 'Cheese Omelette',
    imageUrl: '/images/products/breakfast/omelette_cheese.webp',
    categoryId: 2,
  },
  {
    id: 5,
    name: 'Mashrooms Starter',
    imageUrl: '/images/products/breakfast/starter_mushrooms.webp',
    categoryId: 2,
  },
  {
    id: 6,
    name: 'Cheese Starter',
    imageUrl: '/images/products/breakfast/starter_cheese.webp',
    categoryId: 2,
  },
  {
    id: 7,
    name: 'Cheese Pancakes',
    imageUrl: '/images/products/breakfast/cheese_pancakes.webp',
    categoryId: 2,
  },
  {
    id: 8,
    name: 'Cheese Pancakes & Cream',
    imageUrl: '/images/products/breakfast/cheese_pancakes_cream.webp',
    categoryId: 2,
  },
  {
    id: 9,
    name: 'Cheese Pancakes & Jam',
    imageUrl: '/images/products/breakfast/cheese_pancakes_jam.webp',
    categoryId: 2,
  },
  // Snaks
  {
    id: 10,
    name: 'Meat Dodster',
    imageUrl: '/images/products/snaks/dodster_meat.webp',
    categoryId: 3,
  },
  {
    id: 11,
    name: 'Ham Dodster',
    imageUrl: '/images/products/snaks/dodster_ham.webp',
    categoryId: 3,
  },
  {
    id: 12,
    name: 'Dodster',
    imageUrl: '/images/products/snaks/dodster.webp',
    categoryId: 3,
  },
  {
    id: 13,
    name: 'Hot Dodster 🌶️🌶️',
    imageUrl: '/images/products/snaks/dodster_hot.webp',
    categoryId: 3,
  },
  {
    id: 14,
    name: 'Chorizo BBQ Danwich',
    imageUrl: '/images/products/snaks/danwich_chorizo.webp',
    categoryId: 3,
  },
  {
    id: 15,
    name: 'Ham & Cheese Danwich',
    imageUrl: '/images/products/snaks/danwich_ham_cheese.webp',
    categoryId: 3,
  },
  {
    id: 16,
    name: 'Chicken Wings BBQ 🌶️',
    imageUrl: '/images/products/snaks/bbq_chicken_wings.webp',
    categoryId: 3,
  },
  {
    id: 17,
    name: 'Pasta Carbonara',
    imageUrl: '/images/products/snaks/pasta_carbonara.webp',
    categoryId: 3,
  },
  {
    id: 18,
    name: 'Pasta Pesto',
    imageUrl: '/images/products/snaks/pasta_pesto.webp',
    categoryId: 3,
  },
  {
    id: 19,
    name: 'Chicken Lunch',
    imageUrl: '/images/products/snaks/chicken_pieces_lunch.webp',
    categoryId: 3,
  },
  {
    id: 20,
    name: 'Chicken Wings',
    imageUrl: '/images/products/snaks/chicken_wings.webp',
    categoryId: 3,
  },
  {
    id: 21,
    name: 'Chicken Pieces',
    imageUrl: '/images/products/snaks/chicken_pieces.webp',
    categoryId: 3,
  },
  {
    id: 22,
    name: 'Chicken Nuggets',
    imageUrl: '/images/products/snaks/chicken_nuggets.webp',
    categoryId: 3,
  },
  {
    id: 23,
    name: 'Potates from oven 🌱',
    imageUrl: '/images/products/snaks/oven_potatoes.webp',
    categoryId: 3,
  },
  {
    id: 24,
    name: 'Potates with sauсe 🌱',
    imageUrl: '/images/products/snaks/potatoes_sauce.webp',
    categoryId: 3,
  },
  // Coffe
  {
    id: 25,
    name: 'Cappuccino',
    imageUrl: '/images/products/coffee/cappuccino.webp',
    categoryId: 4,
  },
  {
    id: 26,
    name: 'Caramel Cappuccino',
    imageUrl: '/images/products/coffee/cappuccino_caramel.webp',
    categoryId: 4,
  },
  {
    id: 27,
    name: 'Americano 🌱',
    imageUrl: '/images/products/coffee/americano.webp',
    categoryId: 4,
  },
  {
    id: 28,
    name: 'Latte',
    imageUrl: '/images/products/coffee/latte.webp',
    categoryId: 4,
  },
  {
    id: 29,
    name: 'Coconut Latte',
    imageUrl: '/images/products/coffee/latte_coconut.webp',
    categoryId: 4,
  },
  {
    id: 30,
    name: 'Hazelnut Latte',
    imageUrl: '/images/products/coffee/latte_hazelnut.webp',
    categoryId: 4,
  },
  // Deserts
  {
    id: 31,
    name: 'Banana Cheesecake',
    imageUrl: '/images/products/desserts/cheesecake_banana_chocolate.webp',
    categoryId: 5,
  },
  {
    id: 32,
    name: 'Mango Macaroni',
    imageUrl: '/images/products/desserts/macaroni_mango.webp',
    categoryId: 5,
  },
  {
    id: 33,
    name: 'NewYork Cheesecake',
    imageUrl: '/images/products/desserts/cheesecake_new_york.webp',
    categoryId: 5,
  },
  {
    id: 34,
    name: 'Chocolate Muffin',
    imageUrl: '/images/products/desserts/muffin_chocolate.webp',
    categoryId: 5,
  },
  {
    id: 35,
    name: 'Fondant',
    imageUrl: '/images/products/desserts/fondant.webp',
    categoryId: 5,
  },
  {
    id: 36,
    name: 'Salted Caramel Muffin',
    imageUrl: '/images/products/desserts/muffin_salted_caramel.webp',
    categoryId: 5,
  },
].map(({ name, imageUrl, categoryId }) => ({ name, imageUrl, categoryId }));